apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: heimdall-pvc
    namespace: default
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/heimdall
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node-01-staging

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
        - name: heimdall
          image: lscr.io/linuxserver/heimdall:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/Sao_Paulo"
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
          ports:
            - name: http-port
              containerPort: 80
            - name: https-port
              containerPort: 443
          volumeMounts:
            - name: heimdall-data
              mountPath: /config
      volumes:
        - name: heimdall-data
          persistentVolumeClaim:
              claimName: heimdall-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: heimdall-svc
spec:
  selector:
    app: heimdall
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30443
